### ISSUE TITLE
Spurious Chapter: 4.10

### ISSUE THREAD

**Issue by dufferzafar** [algmyr/e-maxx-eng-book#2]
In the latest PDF: http://web.student.chalmers.se/%7Ealgmyr/upload/e-maxx.pdf

There is a spurious chapter (4.10) that shouldn't be there.

It's coming from the last section of above chapter (Palindromes)

**Comment by algmyr** [comment]
Apparently some problem listings were sections rather than subsections. Made a pull request to fix that. So this should be fixed now.

**Comment by dufferzafar** [comment]
Thanks for the quick response :)
