### ISSUE TITLE
Generate unique labels to subsections and lower

### ISSUE THREAD

**Issue by algmyr** [algmyr/e-maxx-eng-book#4]
This is not really useful for referring to sections, but it would stop LaTeX from complaining about multiple references. Could probably be implemented using a unique per file prefix for labels, i.e. solve #3 and this should be easy to do as well.

**Comment by algmyr** [comment]
Fixed by 640d01ab84107f13b875367fc6b16d02f3f56302 and e669aae584cfebad8ef81844398431a462f4d2d2

**Comment by dufferzafar** [comment]
@algmyr Some sections have such headers: https://github.com/e-maxx-eng/e-maxx-eng/blob/master/src/data_structures/segment_tree.md#implementation--implementation

So they show up in the PDF as: `Implementation ### {#implementation}` 

instead of just `Implementation`

**Comment by algmyr** [comment]
Well, damn. I guess I shouldn't add a label if there is already one there. Let's re-open this for now, I'll see if I can get that fixed easily.

**Comment by dufferzafar** [comment]
I'll admit that I did try doing this, for like 5-10 minutes, but couldn't come up with a regex, and I can't perl so I'll leave it to you :)

**Comment by algmyr** [comment]
@dufferzafar 
You're implying I know perl well. :P
I really only picked perl because sed was giving me trouble for a while. Now I'm glad I moved over since I can actually easily add something like an if statement between the regex I use, which is really handy in this case.

In any case, I think I have a decent fix going. It skips generating labels if labels are already there, which fixes the problem with the section you showed. It also makes it so that links going to manually labeled sections actually work (like the link to Implementation in the Segment Tree article).

However, it will not work for links that assume that a `# Section Title` by default has label `section-title`. I hope that's an ok trade-off, it will require some changes to articles that assume the above (like the "Advanced versions" link in the Segment Tree article). In that case there was an html anchor added, but there needs to be a proper markdown label as well. It'll only need to be there if someone actually wants to refer to that subsection, so it's easy to add when it's needed, otherwise a label will be generated.

Could you try the testing branch and see if things work as expected?

**Comment by algmyr** [comment]
It looks ok to me, so I'll merge it into master. Just leave a comment if you find anything odd.
