### ISSUE TITLE
Publish pdf to releases

### ISSUE THREAD

**Issue by optozorax** [algmyr/e-maxx-eng-book#6]
There is a section called [releases](https://github.com/algmyr/e-maxx-eng-book/releases) made exactly for publishing a compiled version of the repository, in this case: the pdf.

https://algmyr.se/upload/e-maxx.pdf is now unavailable, and so the GitHub releases will be much stable.

**Comment by algmyr** [comment]
That's an issue on my part, sorry. I don't have a static IP with my ISP, so my website is a bit flaky. I made a release now and pushed some general fixes.
