### ISSUE TITLE
grep: invalid option

### ISSUE THREAD

**Issue by filipemsilv4** [algmyr/e-maxx-eng-book#8]
I'm getting this error when running misc/imgfetch.sh on macOS 13.4 (M1):
```
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
bash-3.2$ misc/imgfetch.sh
```

**Comment by algmyr** [comment]
Yeah, this is written assuming it's GNU grep, which isn't the case on MacOS.

**Comment by algmyr** [comment]
Looking at the regex it looks like it might just work with `E` instead of `P`. Try it out, if it works feel free to make a small PR to change it

**Comment by filipemsilv4** [comment]
Yeah, this solves the issue.
